[2025-07-17T18:29:20.335+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-17T18:29:20.360+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_model_training.train_and_log_model scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-17T18:29:20.368+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_model_training.train_and_log_model scheduled__2025-07-16T00:00:00+00:00 [queued]>
[2025-07-17T18:29:20.370+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-17T18:29:20.385+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_and_log_model> on 2025-07-16 00:00:00+00:00
[2025-07-17T18:29:20.393+0000] {standard_task_runner.py:63} INFO - Started process 215 to run task
[2025-07-17T18:29:20.396+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_model_training', 'train_and_log_model', 'scheduled__2025-07-16T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/flight_model_dag.py', '--cfg-path', '/tmp/tmpqhmr39gs']
[2025-07-17T18:29:20.399+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask train_and_log_model
[2025-07-17T18:29:20.455+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_model_training.train_and_log_model scheduled__2025-07-16T00:00:00+00:00 [running]> on host ec77630edb53
[2025-07-17T18:29:20.546+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_model_training' AIRFLOW_CTX_TASK_ID='train_and_log_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-16T00:00:00+00:00'
[2025-07-17T18:29:20.548+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-17T18:30:18.142+0000] {logging_mixin.py:188} WARNING - 2025/07/17 18:30:18 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-07-17T18:30:20.449+0000] {logging_mixin.py:188} WARNING - 2025/07/17 18:30:20 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
[2025-07-17T18:30:26.920+0000] {logging_mixin.py:188} WARNING - 2025/07/17 18:30:26 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-07-17T18:30:28.478+0000] {logging_mixin.py:188} INFO - üèÉ View run unleashed-smelt-937 at: http://mlflow:5000/#/experiments/474368820096796256/runs/250d1477073042569fc8c7068e70fe05
[2025-07-17T18:30:28.479+0000] {logging_mixin.py:188} INFO - üß™ View experiment at: http://mlflow:5000/#/experiments/474368820096796256
[2025-07-17T18:30:29.369+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-17T18:30:29.371+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-17T18:30:29.383+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flight_model_training, task_id=train_and_log_model, run_id=scheduled__2025-07-16T00:00:00+00:00, execution_date=20250716T000000, start_date=20250717T182920, end_date=20250717T183029
[2025-07-17T18:30:29.444+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-17T18:30:29.472+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-17T18:30:29.492+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
